### PR TITLE
Added new function Get-NixKernel

### PR DESCRIPTION
**Pull request by alaurie**
Get-NixKernel uses the hostnamectl utility to get the kernel and arch and returns a pscustomobject. Couldn't figure out the exout formatting stuff and thought returning a native object should be good for just two line.

Let me know of any feedback on the formatting front.

### CODE REVIEW

**Comment by StartAutomating** [comment]
@alaurie thanks for submitting a PR and adding some new functionality:

I'd love to see some changes before we merge:
1. hostnamectl looks like it's used to get information about the given host.    This is great information to be able to easily access thru the object pipeline, and I'd love to expose it.  I just think that Get-NixKernel isn't the right name of that function.  I'm thinking either Get-NixHost or Get-NixComputer
2. It would be great to include all output from hostnamectl.  To do this, I'd recommend looping over each line in the output and splitting them on colons, e.g. ```$key,value = $line -split ':', 2; $key = "$key".Trim(); $value = "$value".Trim() ``` .  
3. Your return object should be decorate with a PSTypeName.  This lets us format the object.  Here's a quick example example of how to do this: ```[PSCustomObject]@{n=1;PSTypeName='PowerNix.ComputerInfo'} ```
4. I'd like to see some brief tests before we merge. Could you please update the exists .tests.ps1 file?
5. Once we're all set, I'd like you to revise the module version.

**Comment by alaurie** [comment]
I'll do a refactor with your suggestions. Funnily enough I originally did it with all the output of hostnamectl with the pstype object but removed it to simplify it. I presume there is nothing to do with the ezout module mentioned as I'll just create a straigh type object in the func?

**Comment by StartAutomating** [comment]
@alaurie the .PSTypeName is used by the format/types subsystem to format the return.  The formatting is written with EZOut.

So these _do_ have something to do with one another.

EZOut is a built-time tool.  It generates format.ps1xml and types.ps1xml files. PowerNix _does not require EZOut_ .Updating formatting for PowerNix does.

Once you've added the decoration, go create a file beneath /Formatting named TYPENAME.format.ps1

In that file, you'd have something like:

Write-FormatView -TypeName "PowerNix.ComputerInfo" -Property a,b,c


This will write a table formatter for the type.

Rerun PowerNix.ezout.ps1 and it will regenerate the format file.

Checkin your .format.ps1 file and the .format.ps1xml, and you should be good.

Does this all make sense?

**Comment by alaurie** [comment]
Updated the function to Get-NixComputer and added type and regenerated the xml with ezout.

I get the pstypename in the first row though.

image

**Comment by StartAutomating** [comment]
It looks like you're outputting things as a [hashtable] or [ordered] dictionary.

I've updated Get-NixComputer to cast to [PSCustomObject] before you output (it should do the trick).

Did you have a chance to make some tests?

**Comment by StartAutomating** [comment]
@alaurie So, this accidentally ended up merging, though it will not publish this version to the gallery yet.

The reason it ended up merging was that I went to help you out a bit and check this code out locally.

Because your branch was named main, git kinda horked and ended up basically updating main when I pushed.

Please open a new PR to revise the version and add a basic test (I'd simply check that you get a machine name ``` `$result.MachineID | should -belike '?*' ```  )

**_Please Do This In a Branch (not named main)_**

**Comment by alaurie** [comment]
No drama, I'll see if I can sort that tonight and do a new PR

**Pull request merged**
